### ISSUE TITLE
 [ERROR] Deluge: json: cannot unmarshal number 314489.59375 into Go struct field Torrent.eta of type int

### ISSUE THREAD

**Issue by slink42** [pyed/transmission-telegram#12]
[ERROR] Deluge: json: cannot unmarshal number 314489.59375 into Go struct field Torrent.eta of type int

Occurs almost every time when attempting any of the list related functions (list, search, head, tail, etc.)

I suspect it is a type cast error where a value is being returned outside the limits of the int datatype.

**Comment by pyed** [comment]
This is Transmission repo.
