### ISSUE TITLE
Send message when download is complete

### ISSUE THREAD

**Issue by JNat** [pyed/transmission-telegram#18]
I think it'd be neat if the bot sent me a message once a torrent completes downloading — granted, it could be considered noise, so maybe it was left out deliberately?

**Comment by pyed** [comment]
actually I implemented that in [pyed/rtelegram](https://github.com/pyed/rtelegram), never had the time to port it here, maybe you could do it.

**Comment by JNat** [comment]
mmm... I'm not familiarized with go, but I'll have a look some time in the coming month and see if I can infer the behaviors from context :)

**Comment by JNat** [comment]
Was starting to dig, to see if I could port it as you'd suggested... Isn't it all [here](https://github.com/pyed/transmission-telegram/blob/master/main.go#L212), already?

Again, not familiarized with go, so I might be missing what it's currently missing.

**Comment by JNat** [comment]
Is it just a matter of copying what's nested inside the function under `if ComLogFile != ""` [here](https://github.com/pyed/rtelegram/blob/master/main.go#L194), so it replaces what's nested inside the function under `if TransLogFile != ""` [here](https://github.com/pyed/transmission-telegram/blob/master/main.go#L212).

Again: not familiarized with go. Also currently unable to try and test this locally myself.

**Comment by JNat** [comment]
Yeah, looks like that's pretty much what's [in your dev branch](https://github.com/pyed/transmission-telegram/compare/dev), @pyed :)

**Comment by pyed** [comment]
Yeah the idea is that I make my torrent client log every completed download to a file, and watch said file for new completed downloads and send a message about them.

**Comment by JNat** [comment]
Yup, I got it from reading those bits of code :)

So if we merge your dev branch, would that do it? Or does it need anything extra?

**Comment by pyed** [comment]
I really can’t recall what I was doing, I’m kinda busy these days, I will take a look into it when I have the time.

**Comment by pyed** [comment]
I had the time to look into it, actually the notification upon completion feature is already here, even though I was using a different tailing package in the `dev` branch.

all you have to do is run your `transmission-daemon` with the `--logfile` option to have a log file, and run `transmission-telegram` with the `-transmission-logfile` flag and point that to the transmission log file, upon the completion of any torrent it should send you a message.

**Comment by JNat** [comment]
Hey, don't you need to trigger a new release for this to propagate to new download, etc.? :)

Or is there some other way for me to get this running with these new changes on a machine that doesn't have golang installed?

**Comment by moToroTor** [comment]
Needs a new build released, the [wiki](https://github.com/pyed/transmission-telegram/wiki) says this feature is out but it's not in the latest release v1.4.
