### ISSUE TITLE
Slight error in indentation in `help` and `stats`

### ISSUE THREAD

**Issue by JNat** [pyed/transmission-telegram#20]
The very first line of `help` is not properly indented; see attached screenshot:

![Screenshot 2019-04-25 at 19 18 32](https://user-images.githubusercontent.com/8878890/56758630-0eee6700-678f-11e9-8a47-afb943e81dad.png)

**Comment by JNat** [comment]
Just noticed the same thing happens in `stats`, so updated the title to reflect that.

**Comment by pyed** [comment]
#22
