### ISSUE TITLE
Works on RaspberryPi 2 via Docker?

### ISSUE THREAD

**Issue by neoranger** [pyed/transmission-telegram#28]
I tried to use this excellent on RaspberyPi 2 via Docker but i can't. I can create the container but when i do the run command i get this in the container's log: standard_init_linux.go:190: exec user process caused "exec format error"

**Comment by pyed** [comment]
@kevinhalpin

**Comment by davidsaraiva** [comment]
I used an ARM image: https://hub.docker.com/r/nawa/transmission-telegram-armhf
