### ISSUE TITLE
Bad url 

### ISSUE THREAD

**Issue by javikobcn** [pyed/transmission-telegram#37]
Hi, i have this error, tried some urls but always same error, the correct url is 192.168.1.XXX:9091 right?
The username and password are corrects 100%

"[ERROR] Transmission: Make sure you have the right URL, Username and Password"

**Comment by pyed** [comment]
`-url= Set to transmission's RPC url, it has to be the full url, starts with http and ends with /rpc.`

**Comment by javikobcn** [comment]
> `-url= Set to transmission's RPC url, it has to be the full url, starts with http and ends with /rpc.`

yes, in the url i have this: -url=http://192.168.1.100:9091/transmission/rpc
but the error persists and also if i try to go to that url in chrome i get a conflict 409 after the login popup 
"409: Conflict
Your request had an invalid session-id header.

To fix this, follow these steps:

When reading a response, get its X-Transmission-Session-Id header and remember it
Add the updated header to your outgoing requests
When you get this 409 error message, resend your request with the updated header
This requirement has been added to help prevent CSRF attacks."

**Comment by javikobcn** [comment]
I close this issue because i solved with a docker-compose file by other user

**Comment by iruahn** [comment]
> I close this issue because i solved with a docker-compose file by other user

I have error like you.
Do you possible to share a docker-compose file to me?

**Comment by javikobcn** [comment]
sure, i have tried this:
https://github.com/pyed/transmission-telegram/issues/25
