### ISSUE TITLE
Ignored messages

### ISSUE THREAD

**Issue by javikobcn** [pyed/transmission-telegram#38]
I got this issue in the log file when i type any message to the bot and nothing happens, what i can do to fix it?
<a href="https://imgur.com/xhP4PpH"><img src="https://i.imgur.com/xhP4PpH.png" title="source: imgur.com" /></a>

**Comment by pyed** [comment]
Make sure you set your master flag right
‘
-master= Your Telegram username, so the bot will answer only to you, you can specify more than one master REQUIRED.
‘

**Comment by javikobcn** [comment]
I have put my telegram ID (numbers) and in the log i got my telegram nickname as ignored

**Comment by javikobcn** [comment]
OK my bad, I tried changing my user id (numbers) by my name id "@myuser" and now works well
