### ISSUE TITLE
Two Masters telegram

### ISSUE THREAD

**Issue by luiscajl** [pyed/transmission-telegram#4]
How is it possible to insert two flags into the master? I have tried in many ways but I never find the right one. 
-master=user1,user2
-master={user1,user2}
-master=(user1,user2)
-master=[user1,user2]
-master={user1:user2}

**Comment by ManuelLR** [comment]
You can do it typing -master= user1 -master=user2

**Comment by luiscajl** [comment]
It does not work, in addition depending on the site where the master goals works for you or one or the other
![printf](https://cloud.githubusercontent.com/assets/9429696/22546583/ffe45cc8-e93d-11e6-8739-6fadc0d000ae.png)

**Comment by pyed** [comment]
You are using an older version, try building HEAD at version 1.3, I will do update the download links with a new release soon.

**Comment by luiscajl** [comment]
Done. Now is working. Thanks 👍
