### ISSUE TITLE
Docker image build problem

### ISSUE THREAD

**Issue by uPagge** [pyed/transmission-telegram#43]
I wanted to build an image for another architecture, but I encountered the following problem:

<img width="999" alt="Снимок экрана 2024-01-28 в 11 06 20" src="https://github.com/pyed/transmission-telegram/assets/40397740/59eda24d-35ce-45a9-babd-43affae877ce">

**Comment by uPagge** [comment]
I fixed it for yourself

https://github.com/pyed/transmission-telegram/pull/44

**Comment by pyed** [comment]
Thank you for your contribution
