### ISSUE TITLE
Download notification

### ISSUE THREAD

**Issue by enzosterro** [pyed/transmission-telegram#6]
I have 1.3 version which I build myself for Raspberry Pi 3 from your source.
I'm running `transmission-daemon` with logging flag.
I'm executing `transmission-telegram -token=XXX -master=XXX -transmission-logfile='transmission.log'` and getting an error:

> flag provided but not defined: -transmission-logfile

Without this flag it works great.

**Comment by enzosterro** [comment]
I guess I got it. Only 1.4 version has `-transmission-logfile` flag.

**Comment by pyed** [comment]
`v1.4` was delayed to fix a couple of issues, you can find the release: https://github.com/pyed/transmission-telegram/releases
