### ISSUE TITLE
not working download notification...

### ISSUE THREAD

**Issue by unbreakhyek** [pyed/transmission-telegram#8]
here is script log...

2017/07/23 16:26:58 [INFO] Token={bot token}
		Masters={name}
		URL={url}
		USER={user}
		PASS={pass}
2017/07/23 16:26:58 Seeked {log dir}/transmission.log - &{Offset:0 Whence:2}
2017/07/23 16:26:59 [INFO] Authorized: {my bot}

i checked from transmission-telegram is seeked transmission.log successfully
and use to 1.4v script.
but bot don't send download stats notification message for me. 
What is the problem?
thx.

**Comment by pyed** [comment]
- Have you messaged the bot at all ?
- Can you find in `{log dir}/transmission.log` lines look like this:
``` [2017-02-22 21:00:00.898] File-Name State changed from "Incomplete" to "Complete" (torrent.c:2218)```

**Comment by unbreakhyek** [comment]
oh... sorry, problem has occurred to transmission log.
transmission log was not working and i fixed message level.
than I solved the problem.
