### ISSUE TITLE
Add functionality to specify download location

### ISSUE THREAD

**Issue by ghost** [pyed/transmission-telegram#9]
Please add command to specify download location.

Thanks

**Comment by ChrisLahaye** [comment]
I add this feature in my fork and created a pull request for it. You can find a release build for ARM here: https://github.com/ChrisLahaye/transmission-telegram/releases

Let me know if it works or if you encounter any problems.

**Comment by deontgn** [comment]
Please add the possibility of specifying a download location in send file dialog. (Text-field: caption)

**Comment by JNat** [comment]
Was this ever implemented, as per the PR @ChrisLahaye mentioned a while back?

**Comment by ThomasF34** [comment]
Hey ! What about this feature ? 👍
